query DiseaseAssociationsQuery(
  $id: String!
  $index: Int!
  $size: Int!
  $sortBy: String!
  $enableIndirect: Boolean!
  $datasources: [DatasourceSettingsInput!]
  $rowsFilter: [String!]
  $facetFilters: [String!]
  $entitySearch: String!
) {
  disease(efoId: $id) {
    id
    name
    associatedTargets(
      page: { index: $index, size: $size }
      orderByScore: $sortBy
      enableIndirect: $enableIndirect
      datasources: $datasources
      Bs: $rowsFilter
      facetFilters: $facetFilters
      BFilter: $entitySearch
    ) {
      count
      rows {
        # --- row metrics (see AssociationsToolkit/static_datasets/rowMetrics.ts) ---
        novelty: noveltyDirect
        # ---------------------------------------------------------------------------
        target {
          id
          approvedSymbol
          approvedName
          prioritisation {
            items {
              key
              value
            }
          }
        }
        score
        datasourceScores {
          componentId: id
          score
        }
      }
    }
  }
}
