language: node_js
node_js:
  - 12
cache: yarn
install:
  - yarn
script:
  - yarn build
after_success:
  - cd build
  - tar czvf ../bundle.tgz *
  - cd ..
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "bundle.tgz"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
