const dataSources = [
  {
    id: 'ot_genetics_portal',
    sectionId: 'otGenetics',
    label: 'OT Genetics Portal',
    aggregation: 'genetic_association',
    weight: 1,
  },
  {
    id: 'eva',
    sectionId: 'eva',
    label: 'ClinVar',
    aggregation: 'genetic_association',
    weight: 1,
  },
  {
    id: 'gene_burden',
    sectionId: 'geneBurden',
    label: 'Gene Burden',
    aggregation: 'genetic_association',
    weight: 1,
  },
  {
    id: 'genomics_england',
    sectionId: 'genomicsEngland',
    label: 'GEL PanelApp',
    aggregation: 'genetic_association',
    weight: 1,
  },
  {
    id: 'gene2phenotype',
    sectionId: 'gene2Phenotype',
    label: 'Gene2phenotype',
    aggregation: 'genetic_association',
    weight: 1,
  },
  {
    id: 'uniprot_literature',
    sectionId: 'uniprotLiterature',
    label: 'UniProt literature',
    aggregation: 'genetic_association',
    weight: 1,
  },
  {
    id: 'uniprot_variants',
    sectionId: 'uniprotVariants',
    label: 'UniProt curated variants',
    aggregation: 'genetic_association',
    weight: 1,
  },
  {
    id: 'orphanet',
    sectionId: 'orphanet',
    label: 'Orphanet',
    aggregation: 'genetic_association',
    weight: 1,
  },
  {
    id: 'clingen',
    sectionId: 'clinGen',
    label: 'Clingen',
    aggregation: 'genetic_association',
    weight: 1,
  },
  {
    id: 'cancer_gene_census',
    sectionId: 'cancerGeneCensus',
    label: 'Cancer Gene Census',
    aggregation: 'somatic_mutations',
    weight: 1,
  },
  {
    id: 'intogen',
    sectionId: 'intOgen',
    label: 'IntOGen',
    aggregation: 'somatic_mutations',
    weight: 1,
  },
  {
    id: 'eva_somatic',
    sectionId: 'evaSomatic',
    label: 'ClinVar (somatic)',
    aggregation: 'somatic_mutations',
    weight: 1,
  },
  {
    id: 'cancer_biomarkers',
    sectionId: 'cancerBiomarkers',
    label: 'Cancer Biomarkers',
    aggregation: 'somatic_mutations',
    weight: 1,
  },
  {
    id: 'chembl',
    sectionId: 'chembl',
    label: 'ChEMBL',
    aggregation: 'known_drug',
    weight: 1,
  },
  {
    id: 'crispr',
    sectionId: 'crispr',
    label: 'Project Score',
    aggregation: 'affected_pathway',
    weight: 1,
  },
  {
    id: 'slapenrich',
    sectionId: 'slapEnrich',
    label: 'SLAPenrich',
    aggregation: 'affected_pathway',
    weight: 0.5,
  },
  {
    id: 'progeny',
    sectionId: 'progeny',
    label: 'PROGENy',
    aggregation: 'affected_pathway',
    weight: 0.5,
  },
  {
    id: 'reactome',
    sectionId: 'reactome',
    label: 'Reactome',
    aggregation: 'affected_pathway',
    weight: 1,
  },
  {
    id: 'sysbio',
    sectionId: 'sysBio',
    label: 'Gene signatures',
    aggregation: 'affected_pathway',
    weight: 0.5,
  },
  {
    id: 'europepmc',
    sectionId: 'europePmc',
    label: 'Europe PMC',
    aggregation: 'literature',
    weight: 0.2,
  },
  {
    id: 'expression_atlas',
    sectionId: 'expression',
    label: 'Expression Atlas',
    aggregation: 'rna_expression',
    weight: 0.2,
  },
  {
    id: 'impc',
    sectionId: 'impc',
    label: 'IMPC',
    aggregation: 'animal_model',
    weight: 0.2,
  },
  {
    id: 'ot_crispr_validation',
    sectionId: 'validationlab',
    label: 'OT CRISPR Validation',
    aggregation: 'ot_validation_lab',
    weight: 0.5,
  },
  // Private
  {
    id: 'ot_crispr',
    sectionId: 'otCrispr',
    label: 'OTAR CRISPR',
    aggregation: 'ot_validation_lab',
    weight: 0.5,
  },
  // Private
  // {
  //   id: 'encore',
  //   sectionId: '',
  //   label: 'ENCORE',
  //   aggregation: 'ot_validation_lab',
  //   weight: 0.5,
  // },
];

export default dataSources;
