language: node_js
node_js:
  - 16
cache: yarn
install:
  - yarn
script:
  - pwd
  - yarn build
after_success:
  - pwd
  - cd bundle-platform
  - tar czvf ../bundle-platform.tgz *
  - cd ..
  - cd bundle-genetics
  - tar czvf ../bundle-genetics.tgz *
  - cd ..
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "bundle-platform.tgz"
    - "bundle-genetics.tgz"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
