language: node_js
node_js:
  - 16
cache: yarn
install:
  - yarn
script:
  - yarn build
after_success:
  - |
    if [$TRAVIS_TAG && $TRAVIS_TAG =~ ^platform.*$ ]; then
      cd dist-platform
      tar czvf ../bundle.tgz *
      cd ..
    fi
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "bundle.tgz"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
