fragment DrugProfileHeaderFragment on Drug {
  description
  drugType
  synonyms {
    label
    source
  }
  parentMolecule {
    id
    name
  }
  childMolecules {
    id
    name
  }
  maximumClinicalStage
  tradeNames {
    label
    source
  }
}
