query TargetAssociationsQuery(
  $ensemblId: String!
  $index: Int!
  $size: Int!
  $filter: String
  $sortBy: String!
  $aggregationFilters: [AggregationFilter!]
  $enableIndirect: Boolean!
) {
  target(ensemblId: $ensemblId) {
    id
    associatedDiseases(
      page: { index: $index, size: $size }
      orderByScore: $sortBy
      BFilter: $filter
      aggregationFilters: $aggregationFilters
      enableIndirect: $enableIndirect
    ) {
      count
      rows {
        disease {
          id
          name
        }
        score
        datasourceScores {
          componentId: id
          score
        }
      }
    }
  }
}
