import { Grid, Typography, Box, Chip, Theme } from "@mui/material";
import { makeStyles, styled, useTheme } from "@mui/styles";
import { Helmet } from "react-helmet";
import { Footer, GlobalSearch, Link, NavBar, usePermissions, useSearchState } from "ui";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faCircle,
  faChevronDown,
  faDownload,
  faLaptopCode,
  faQuestionCircle,
  faFileAlt,
  faCommentDots,
  faStethoscope,
  faDna,
  faPrescriptionBottleMedical,
  faMapPin,
  faChartBar,
  faSquare,
} from "@fortawesome/free-solid-svg-icons";
import { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import { grey } from "@mui/material/colors";
import { getConfig } from "@ot/config";
import {
  appTitle,
  appDescription,
  appCanonicalUrl,
  externalLinks,
  mainMenuItems,
} from "@ot/constants";
import HomeBox from "./HomeBox";
import Splash from "./Splash";
import Version from "./Version";

const config = getConfig();

const useStyles = makeStyles<Theme>(() => ({
  links: {
    marginTop: "12px",
  },
  api: {
    marginTop: "38px",
  },
  dataPolicy: {
    padding: "10px",
    marginTop: "30px",
    border: "2px solid",
    borderColor: config.profile.primaryColor as string,
  },
}));

const StyledChip = styled(Chip)(({ theme }) => ({
  border: 1,
  fontSize: "12px",
  fontWeight: "bold",
  boxShadow: 0,
  "&:hover": {
    color: theme.palette.primary.dark,
    background: grey[100],
  },
  "&:hover .MuiChip-icon": {
    color: theme.palette.primary.dark,
  },
}));

function AboutPPP(): JSX.Element {
  return (
    <>
      <Typography paragraph>
        The Open Targets Partner Preview Platform is an extension of the Open Targets Platform, a
        comprehensive tool that supports systematic identification and prioritisation of potential
        therapeutic drug targets.
      </Typography>

      <Typography paragraph>
        Combining publicly available datasets with pre-publication data generated by the consortium,
        the Partner Preview Platform builds and scores target-disease associations to assist in drug
        target identification and prioritisation. It also integrates relevant annotation information
        about targets, diseases, phenotypes, and drugs, as well as their most relevant
        relationships.
      </Typography>

      <Typography paragraph>
        The Partner Preview version of the Open Targets Platform is only available to members of the
        Open Targets consortium. It is actively maintained with regular data updates. Data is
        available through an intuitive user interface, and a partner-specific API which includes the
        pre-publication data. The public data is available through data downloads, while
        pre-publication data can be requested through the intranet (home.opentargets.org). The
        pipeline and infrastructure codebases are open-source and the licence allows the creation of
        self-hosted private instances of the Platform with custom data.
      </Typography>
    </>
  );
}

function AboutPublic(): JSX.Element {
  return (
    <>
      <Typography paragraph>
        The Open Targets Platform is a comprehensive tool that supports systematic identification
        and prioritisation of potential therapeutic drug targets.
      </Typography>

      <Typography paragraph>
        By integrating publicly available datasets including data generated by the Open Targets
        consortium, the Platform builds and scores target-disease associations to assist in drug
        target identification and prioritisation. It also integrates relevant annotation information
        about targets, diseases or phenotypes, variants, GWAS studies and drugs, as well as their
        most relevant relationships.
      </Typography>

      <Typography paragraph>
        The Platform is a freely available resource that is actively maintained with quarterly data
        updates. Data is available through an intuitive user interface, an API, and data downloads.
        The pipeline and infrastructure codebases are open-source and the licence allows the
        creation of self-hosted private instances of the Platform with custom data.
      </Typography>
    </>
  );
}

interface HelpBoxPanelProps {
  fai: IconDefinition;
  url: string;
  label: string;
  external?: boolean;
}

function HelpBoxPanel({ fai, url, label, external = false }: HelpBoxPanelProps): JSX.Element {
  const theme: Theme = useTheme();
  return (
    <Box
      sx={{
        maxWidth: { md: "150px", xs: "200px" },
      }}
    >
      <Link to={url} external={external}>
        <Box sx={{ gap: 1, display: "flex", flexDirection: "column", alignItems: "center" }}>
          <div className="fa-layers fa-fw fa-6x">
            <FontAwesomeIcon icon={faSquare} color={theme.palette.primary.dark} />
            <FontAwesomeIcon icon={fai} transform="shrink-8" inverse />
          </div>
          <Typography align="center" variant="subtitle1" component="div">
            {label}
          </Typography>
        </Box>
      </Link>
    </Box>
  );
}

interface SearchSuggestion {
  id: string;
  name: string;
}

function HomePage(): JSX.Element {
  const { searchSuggestions } = useSearchState() as { searchSuggestions: SearchSuggestion[] };
  const { isPartnerPreview } = usePermissions();
  const releaseNotesURL = isPartnerPreview
    ? "http://home.opentargets.org/ppp-release-notes"
    : "https://platform-docs.opentargets.org/release-notes";
  const classes = useStyles();

  const handleScrollDown = (): void => {
    window.scrollTo({ top: window.innerHeight, left: 0, behavior: "smooth" });
  };

  return (
    <>
      <Helmet title={appTitle}>
        <meta name="description" content={appDescription} />
        <link rel="canonical" href={appCanonicalUrl} />
      </Helmet>
      <Grid container justifyContent="center" alignItems="center" className={classes.hpSection}>
        <Splash />
        {/* <NavBar name="platform" homepage items={mainMenuItems} placement="bottom-end" /> */}
        {/* <HomeBox>
          <GlobalSearch isHomePage />
          {/* Search examples 
          <Grid
            className={classes.links}
            container
            justifyContent="center"
            gap={1.5}
            sx={{ mt: 4 }}
          >
            <Link asyncTooltip to={`/target/${searchSuggestions[0].id}/associations`}>
              <StyledChip
                sx={{ pl: 1, borderRadius: 2 }}
                icon={<FontAwesomeIcon icon={faDna} />}
                label={searchSuggestions[0].name}
              />
            </Link>
            <Link asyncTooltip to={`/target/${searchSuggestions[1].id}/associations`}>
              <StyledChip
                sx={{ pl: 1, borderRadius: 2 }}
                icon={<FontAwesomeIcon icon={faDna} />}
                label={searchSuggestions[1].name}
              />
            </Link>
            <Link asyncTooltip to={`/disease/${searchSuggestions[2].id}/associations`}>
              <StyledChip
                sx={{ pl: 1, borderRadius: 2 }}
                icon={<FontAwesomeIcon icon={faStethoscope} />}
                label={searchSuggestions[2].name}
              />
            </Link>
            <Link asyncTooltip to={`/disease/${searchSuggestions[3].id}/associations`}>
              <StyledChip
                sx={{ pl: 1, borderRadius: 2 }}
                icon={<FontAwesomeIcon icon={faStethoscope} />}
                label={searchSuggestions[3].name}
              />
            </Link>
            <Link asyncTooltip to={`/drug/${searchSuggestions[4].id}`}>
              <StyledChip
                sx={{ pl: 1, borderRadius: 2 }}
                icon={<FontAwesomeIcon icon={faPrescriptionBottleMedical} />}
                label={searchSuggestions[4].name}
              />
            </Link>
            <Link asyncTooltip to={`/drug/${searchSuggestions[5].id}`}>
              <StyledChip
                sx={{ pl: 1, borderRadius: 2 }}
                icon={<FontAwesomeIcon icon={faPrescriptionBottleMedical} />}
                label={searchSuggestions[5].name}
              />
            </Link>
            <Link asyncTooltip to={`/variant/${searchSuggestions[6].id}`}>
              <StyledChip
                sx={{ pl: 1, borderRadius: 2 }}
                icon={<FontAwesomeIcon icon={faMapPin} />}
                label={searchSuggestions[6].name}
              />
            </Link>
            <Link asyncTooltip to={`/variant/${searchSuggestions[7].id}`}>
              <StyledChip
                sx={{ pl: 1, borderRadius: 2 }}
                icon={<FontAwesomeIcon icon={faMapPin} />}
                label={searchSuggestions[7].name}
              />
            </Link>
            <Link asyncTooltip to={`/study/${searchSuggestions[8].id}`}>
              <StyledChip
                sx={{ pl: 1, borderRadius: 2 }}
                icon={<FontAwesomeIcon icon={faChartBar} />}
                label={searchSuggestions[8].name}
              />
            </Link>
            <Link asyncTooltip to={`/study/${searchSuggestions[9].id}`}>
              <StyledChip
                sx={{ pl: 1, borderRadius: 2 }}
                icon={<FontAwesomeIcon icon={faChartBar} />}
                label={searchSuggestions[9].name}
              />
            </Link>
          </Grid>
          <div>
            <Version releaseNotesURL={releaseNotesURL} />
          </div>
        </HomeBox> */}

        {/* scroll down button */}
        {/* <Grid container justifyContent="center">
          <div
            className="fa-layers fa-fw fa-3x"
            style={{
              height: "0px",
              marginTop: "-1em",
              filter: "drop-shadow( 1px 1px 2px rgba(0, 0, 0, .5))",
              cursor: "pointer",
            }}
            onClick={handleScrollDown}
          >
            <FontAwesomeIcon icon={faCircle} inverse />
            <FontAwesomeIcon icon={faChevronDown} transform="shrink-4" />
          </div>
        </Grid> */}
      </Grid>

      {/* About */}

      <Grid container justifyContent="center" sx={{ my: 10 }}>
        <Grid item xs={10} md={8} sx={{ my: 2 }}>
          <Typography variant="h4" component="h1" align="center" paragraph mb={5}>
            About the Open Targets Platform
          </Typography>
          {isPartnerPreview ? <AboutPPP /> : <AboutPublic />}
        </Grid>
      </Grid>

      {/* Get started */}
      <Grid container justifyContent="center" sx={{ mb: 18 }}>
        <Grid item xs={10} md={8}>
          <Typography variant="h4" component="h1" align="center" paragraph mb={5}>
            Get started with the Platform
          </Typography>

          <Box
            sx={{
              display: "flex",
              justifyContent: "space-between",
              gap: { xs: 5, md: 1 },
              alignItems: { xs: "center", md: "flex-start" },
              flexDirection: {
                xs: "column",
                md: "row",
              },
            }}
          >
            <HelpBoxPanel
              fai={faDownload}
              url="/downloads"
              label="Download all of our open datasets"
            />

            <HelpBoxPanel
              fai={faLaptopCode}
              url="/api"
              label="Access data with our GraphQL API"
              external
            />

            <HelpBoxPanel
              fai={faQuestionCircle}
              url="https://platform-docs.opentargets.org/"
              label="Check out our Platform documentation"
              external
            />

            <HelpBoxPanel
              fai={faFileAlt}
              url="https://platform-docs.opentargets.org/citation"
              label="Read our latest Platform publications"
              external
            />

            <HelpBoxPanel
              fai={faCommentDots}
              url="https://community.opentargets.org/"
              label="Join the Open Targets Community"
              external
            />
          </Box>
        </Grid>
      </Grid>

      <Footer externalLinks={externalLinks} />
    </>
  );
}

export default HomePage;
