query StudyPageQuery($studyId: String!) {
  gwasStudy(studyId: $studyId) {
    studyId
    studyType
    projectId
    backgroundTraits {
      id
      name
    }
    target {
      id
    }
    diseases {
      id
      name
    }
  }
}
