fragment StudyProfileHeaderFragment on Study {
  studyType
  publicationFirstAuthor
  publicationDate
  publicationJournal
  pubmedId
  traitFromSource
  projectId
  backgroundTraits {
    id
    name
  }
  diseases {
    id
    name
  }
  target {
    id
    approvedSymbol
  }
  nSamples
  initialSampleSize
  nCases
  nControls
  cohorts
  ldPopulationStructure {
    ldPopulation
    relativeSampleSize
  }
  hasSumstats
  sumstatQCValues {
    QCCheckName
    QCCheckValue
  }
  qualityControls
  analysisFlags
  biosample {
    biosampleId
    biosampleName
  }
  condition
}
