fragment StudyProfileHeaderFragment on Gwas {
  publicationFirstAuthor
  publicationDate
  publicationJournal
  pubmedId
  traitFromSource
  backgroundTraits {
    id
    name
  }
  diseases {
    id
    name
  }
  nSamples
  initialSampleSize
  replicationSamples {
    sampleSize
    ancestry
  }
  nCases
  nControls
  cohorts
  ldPopulationStructure {
    ldPopulation
    relativeSampleSize
  }
  hasSumstats
  sumstatQCValues {
    QCCheckName
    QCCheckValue
  }
  qualityControls
  analysisFlags
  discoverySamples {
    sampleSize
    ancestry
  }
}
