query GWASLeadVariantsPheWASSectionQuery($variantId: String!) {
  indexVariantsAndStudiesForTagVariant(variantId: $variantId) {
    associations {
      indexVariant {
        id
        rsId
      }
    }
  }
}
