query TagVariantPheWASSectionQuery($variantId: String!) {
  tagVariantsAndStudiesForIndexVariant(variantId: $variantId) {
    associations {
      tagVariant {
        id
        rsId
      }
    }
  }
}
