query CredibleSetPageQuery($studyLocusIds: [String!]!) {
  credibleSets(studyLocusIds: $studyLocusIds) {
    variant {
      id,
      referenceAllele,
      alternateAllele
    }
    study {
      studyId
    }
  }
}