fragment CredibleSetProfileHeaderFragment on credibleSet {
  pValueMantissa
  pValueExponent
  beta
  standardError
  effectAlleleFrequencyFromSource
  locus {
    posteriorProbability
    variant {
      id
    }
  }
  variant {
    chromosome
    position
    rsIds
  }
  finemappingMethod
  credibleSetIndex
  purityMinR2
  locusStart
  locusEnd
  study {
    publicationFirstAuthor
    publicationDate
    traitFromSource
    target {
      id
      approvedSymbol
    }
    biosample {
      biosampleId
    }
    publicationJournal
    pubmedId
    nSamples
  }
}