fragment VariantProfileHeaderFragment on Variant {
  chromosome
  position
  referenceAllele
  alternateAllele
  alleleFrequencies {
    populationName
    alleleFrequency
  }
  mostSevereConsequence {
    id
    label
  }
}
