query GWASStudiesQuery {
  studies(diseaseIds: "MONDO_0008383") {
    count
    rows {
      id
      projectId
      traitFromSource
      publicationFirstAuthor
      publicationDate
      publicationJournal
      nSamples
      cohorts
      pubmedId
      ldPopulationStructure {
        ldPopulation
        relativeSampleSize
      }
    }
  }
}
