query APIPagePPPAssociatedDisease {
  disease(efoId: "MONDO_0005180") {
    id
    name
    otarProjects {
      projectName
      status
      integratesInPPP
    }
    associatedTargets {
      count
      rows {
        target {
          id
          approvedSymbol
        }
        score
      }
    }
  }
}