name: Deploy Docs to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - "packages/platform-test/POM/objects/widgets/**"
      - "packages/platform-test/docs/**"
      - "packages/platform-test/typedoc.json"
      - "packages/platform-test/tsconfig.docs.json"
      - ".github/workflows/deploy-docs.yaml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Docs 📚
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 23

      - uses: mskelton/setup-yarn@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate docs
        run: yarn docs:test_interactors

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/platform-test/docs/widgets-api

  deploy:
    name: Deploy to GitHub Pages 🚀
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
